apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-server
  namespace: uhrp-storage
  labels:
    app: storage-server
    app.kubernetes.io/name: storage-server
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: uhrp-storage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: storage-server
  template:
    metadata:
      labels:
        app: storage-server
        app.kubernetes.io/name: storage-server
        app.kubernetes.io/component: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: storage-server
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: storage-server
        image: YOUR_ECR_URL/uhrp-storage-server:latest  # Will be replaced by CI/CD
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: storage-server-config
              key: NODE_ENV
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: storage-server-config
              key: HTTP_PORT
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: storage-server-config
              key: AWS_REGION
        - name: AWS_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: storage-server-config
              key: AWS_BUCKET_NAME
        - name: SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: storage-server-config
              key: SERVER_URL
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: storage-server-config
              key: CORS_ORIGIN
        - name: BSV_NETWORK
          valueFrom:
            configMapKeyRef:
              name: storage-server-config
              key: BSV_NETWORK
        - name: WALLET_STORAGE_URL
          valueFrom:
            configMapKeyRef:
              name: storage-server-config
              key: WALLET_STORAGE_URL
        - name: PER_BYTE_PRICE
          valueFrom:
            configMapKeyRef:
              name: storage-server-config
              key: PER_BYTE_PRICE
        - name: BASE_PRICE
          valueFrom:
            configMapKeyRef:
              name: storage-server-config
              key: BASE_PRICE
        - name: MIN_HOSTING_MINUTES
          valueFrom:
            configMapKeyRef:
              name: storage-server-config
              key: MIN_HOSTING_MINUTES
        - name: SERVER_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: uhrp-secrets
              key: server-private-key
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: uhrp-secrets
              key: admin-token
        - name: BUGSNAG_API_KEY
          valueFrom:
            secretKeyRef:
              name: uhrp-secrets
              key: bugsnag-api-key
              optional: true
        - name: NOTIFIER_URL
          value: "http://event-handler.uhrp-storage.svc.cluster.local:8081/notify"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - storage-server
              topologyKey: kubernetes.io/hostname