name: Build and Push to GHCR

on:
  push:
    tags:
      - "v*"
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  get_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Determine deployment tag
        id: deployment_tag
        run: |
          if [[ '${{ github.ref_type }}' == 'tag' ]]; then
            export tag=${{ github.ref_name }}
            echo "version tag is $tag"
            echo "id=$tag" >> $GITHUB_OUTPUT
          else
            export tag=latest
            echo "version tag is $tag"
            echo "id=$tag" >> $GITHUB_OUTPUT
          fi
    outputs:
      deployment_tag: ${{ steps.deployment_tag.outputs.id }}

  build-and-push:
    needs: [ get_tag ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context (root directory, adjust if Dockerfile is elsewhere)
          file: ./Dockerfile # Path to Dockerfile
          # push: ${{ github.event_name != 'pull_request' }} # Only push on push events, not PRs
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ needs.get_tag.outputs.deployment_tag }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./k8s/s3-event-handler # Build context (root directory, adjust if Dockerfile is elsewhere)
          file: ./k8s/s3-event-handler/Dockerfile # Path to Dockerfile
          # push: ${{ github.event_name != 'pull_request' }} # Only push on push events, not PRs
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-s3-notifier:${{ github.sha }}
            ghcr.io/${{ github.repository }}-s3-notifier:${{ needs.get_tag.outputs.deployment_tag }}

